var db_gpu = [
    ["<img src=\"img/GPU/0.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">INNO3D 3GB</p>",
        "50",
        "12501",
        "<div id=\"\"class=\"ui inverted violet button dr_priceButton\">234680</div>"],
    ["<img src=\"img/GPU/1.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">리드텍 3GB</p>",
        "51",
        "12534",
        "<div class=\"ui inverted violet button dr_priceButton\">302790</div>"],
    ["<img src=\"img/GPU/2.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">GIGABYTE 3GB</p>",
        "54",
        "12986",
        "<div class=\"ui inverted violet button dr_priceButton\">350700</div>"],
    ["<img src=\"img/GPU/3.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">리드텍 6GB</p>",
        "60",
        "13227",
        "<div class=\"ui inverted violet button dr_priceButton\">398790</div>"],
    ["<img src=\"img/GPU/4.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">ZOTAC 6GB</p>",
        "62",
        "13416",
        "<div class=\"ui inverted violet button dr_priceButton\">411280</div>"],
    ["<img src=\"img/GPU/5.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">MSI 6GB</p>",
        "64",
        "13704",
        "<div class=\"ui inverted violet button dr_priceButton\">449400</div>"],
    ["<img src=\"img/GPU/6.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">ASUS 6GB</p>",
        "66",
        "13992",
        "<div class=\"ui inverted violet button dr_priceButton\">465150</div>"],
    ["<img src=\"img/GPU/7.jpg\" class=\"dr_itemImage\">",
        "<p>RX580</p><p class=\"dr_align_right\">SAPPHIRE 8GB</p>",
        "67",
        "14322",
        "<div class=\"ui inverted violet button dr_priceButton\">487000</div>"]
];

var db_cpu = [
    ["<img src=\"img/CPU/0.jpg\" class=\"dr_itemImage\">",
        "<p>펜티엄 G4560</p><p class=\"dr_align_right\">인텔</p>",
        "41",
        "12501",
        "<div id=\"\"class=\"ui inverted violet button dr_priceButton\">118870</div>"],
    ["<img src=\"img/CPU/1.jpg\" class=\"dr_itemImage\">",
        "<p>라이젠 3 2200G</p><p class=\"dr_align_right\">AMD</p>",
        "57",
        "12534",
        "<div class=\"ui inverted violet button dr_priceButton\">168010</div>"],
    ["<img src=\"img/CPU/2.jpg\" class=\"dr_itemImage\">",
        "<p>i3 8100</p><p class=\"dr_align_right\">인텔</p>",
        "60",
        "12986",
        "<div class=\"ui inverted violet button dr_priceButton\">211040</div>"],
    ["<img src=\"img/CPU/3.jpg\" class=\"dr_itemImage\">",
        "<p>라이젠 5 2400G</p><p class=\"dr_align_right\">AMD</p>",
        "61",
        "13227",
        "<div class=\"ui inverted violet button dr_priceButton\">243010</div>"],
    ["<img src=\"img/CPU/4.jpg\" class=\"dr_itemImage\">",
        "<p>i5 8500</p><p class=\"dr_align_right\">인텔</p>",
        "66",
        "13416",
        "<div class=\"ui inverted violet button dr_priceButton\">308560</div>"],
    ["<img src=\"img/CPU/5.jpg\" class=\"dr_itemImage\">",
        "<p>라이젠 5 2600</p><p class=\"dr_align_right\">AMD</p>",
        "63",
        "13704",
        "<div class=\"ui inverted violet button dr_priceButton\">306220</div>"],
    ["<img src=\"img/CPU/6.jpg\" class=\"dr_itemImage\">",
        "<p>i5 8600</p><p class=\"dr_align_right\">인텔</p>",
        "67",
        "13992",
        "<div class=\"ui inverted violet button dr_priceButton\">333930</div>"],
    ["<img src=\"img/CPU/7.jpg\" class=\"dr_itemImage\">",
        "<p>라이젠 5 2600X</p><p class=\"dr_align_right\">AMD</p>",
        "65",
        "14322",
        "<div class=\"ui inverted violet button dr_priceButton\">345220</div>"]
];