var db_gpu = [
    ["<img src=\"img/GPU/0.jpg\" class=\"dr_itemImage\">",
        "<p>ZOTAC GTX1050Ti 4GB</p><p class=\"dr_align_right\">DUALSILENCER OC</p>",
        "38",
        "7655",
        "<div id=\"\"class=\"ui inverted violet button dr_priceButton\">234680</div>"],
    ["<img src=\"img/GPU/1.jpg\" class=\"dr_itemImage\">",
        "<p>리드텍 GTX1060 3GB</p><p class=\"dr_align_right\">Winfast HURRICANE OC</p>",
        "51",
        "12534",
        "<div class=\"ui inverted violet button dr_priceButton\">302790</div>"],
    ["<img src=\"img/GPU/2.jpg\" class=\"dr_itemImage\">",
        "<p>GIGABYE GTX1060 3GB</p><p class=\"dr_align_right\">G1.Gaming</p>",
        "54",
        "12986",
        "<div class=\"ui inverted violet button dr_priceButton\">350700</div>"],
    ["<img src=\"img/GPU/3.jpg\" class=\"dr_itemImage\">",
        "<p>리드텍 GTX1060 6GB</p><p class=\"dr_align_right\">Winfast Hurricane OC</p>",
        "60",
        "13227",
        "<div class=\"ui inverted violet button dr_priceButton\">398790</div>"],
    ["<img src=\"img/GPU/4.jpg\" class=\"dr_itemImage\">",
        "<p>ZOTAC GTX1060 6GB</p><p class=\"dr_align_right\">AMP 백플레이트</p>",
        "62",
        "13416",
        "<div class=\"ui inverted violet button dr_priceButton\">411280</div>"],
    ["<img src=\"img/GPU/5.jpg\" class=\"dr_itemImage\">",
        "<p>MSI GTX1060 6GB</p><p class=\"dr_align_right\">트윈프로져6</p>",
        "64",
        "13704",
        "<div class=\"ui inverted violet button dr_priceButton\">449400</div>"],
    ["<img src=\"img/GPU/6.jpg\" class=\"dr_itemImage\">",
        "<p>ASUS GTX1060 6GB</p><p class=\"dr_align_right\">ROG STRIX O6G GAMING</p>",
        "66",
        "13992",
        "<div class=\"ui inverted violet button dr_priceButton\">465150</div>"],
    ["<img src=\"img/GPU/7.jpg\" class=\"dr_itemImage\">",
        "<p>SAPPHIRE RX580 8GB</p><p class=\"dr_align_right\">NITRO+ OC DUAL-X</p>",
        "67",
        "14322",
        "<div class=\"ui inverted violet button dr_priceButton\">487000</div>"]
];

var db_cpu = [
    ["<img src=\"img/CPU/0.jpg\" class=\"dr_itemImage\">",
        "<p>ZOTAC GTX1050Ti 4GB</p><p class=\"dr_align_right\">DUALSILENCER OC</p>",
        "38",
        "7655",
        "<div id=\"\"class=\"ui inverted violet button dr_priceButton\">234680</div>"],
    ["<img src=\"img/CPU/1.jpg\" class=\"dr_itemImage\">",
        "<p>리드텍 GTX1060 3GB</p><p class=\"dr_align_right\">Winfast HURRICANE OC</p>",
        "51",
        "12534",
        "<div class=\"ui inverted violet button dr_priceButton\">302790</div>"],
    ["<img src=\"img/CPU/2.jpg\" class=\"dr_itemImage\">",
        "<p>GIGABYE GTX1060 3GB</p><p class=\"dr_align_right\">G1.Gaming</p>",
        "54",
        "12986",
        "<div class=\"ui inverted violet button dr_priceButton\">350700</div>"],
    ["<img src=\"img/CPU/3.jpg\" class=\"dr_itemImage\">",
        "<p>리드텍 GTX1060 6GB</p><p class=\"dr_align_right\">Winfast Hurricane OC</p>",
        "60",
        "13227",
        "<div class=\"ui inverted violet button dr_priceButton\">398790</div>"],
    ["<img src=\"img/CPU/4.jpg\" class=\"dr_itemImage\">",
        "<p>ZOTAC GTX1060 6GB</p><p class=\"dr_align_right\">AMP 백플레이트</p>",
        "62",
        "13416",
        "<div class=\"ui inverted violet button dr_priceButton\">411280</div>"],
    ["<img src=\"img/CPU/5.jpg\" class=\"dr_itemImage\">",
        "<p>MSI GTX1060 6GB</p><p class=\"dr_align_right\">트윈프로져6</p>",
        "64",
        "13704",
        "<div class=\"ui inverted violet button dr_priceButton\">449400</div>"],
    ["<img src=\"img/CPU/6.jpg\" class=\"dr_itemImage\">",
        "<p>ASUS GTX1060 6GB</p><p class=\"dr_align_right\">ROG STRIX O6G GAMING</p>",
        "66",
        "13992",
        "<div class=\"ui inverted violet button dr_priceButton\">465150</div>"],
    ["<img src=\"img/CPU/7.jpg\" class=\"dr_itemImage\">",
        "<p>SAPPHIRE RX580 8GB</p><p class=\"dr_align_right\">NITRO+ OC DUAL-X</p>",
        "67",
        "14322",
        "<div class=\"ui inverted violet button dr_priceButton\">487000</div>"]
];