
var dbr_gpu = [
    ["<img src=\"img/GPU/0.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1050Ti</p><p class=\"dr_align_right\">ZOTAC 4GB</p>",
        "33",
        "942",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,true,0);' id=\"\"class=\"ui inverted violet button dr_priceButton texts\">233770</div>"],
    ["<img src=\"img/GPU/1.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">리드텍 3GB</p>",
        "45",
        "1083",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,true,1);' class=\"ui inverted violet button dr_priceButton texts\">302790</div>"],
    ["<img src=\"img/GPU/2.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">GIGABYTE 3GB</p>",
        "47",
        "1118",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,true,2);' class=\"ui inverted violet button dr_priceButton texts\">350700</div>"],
    ["<img src=\"img/GPU/3.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">리드텍 6GB</p>",
        "51",
        "1222",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,true,3);' class=\"ui inverted violet button dr_priceButton texts\">398790</div>"],
    ["<img src=\"img/GPU/4.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">ZOTAC 6GB</p>",
        "52",
        "1256",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,true,4);' class=\"ui inverted violet button dr_priceButton texts\">411280</div>"],
    ["<img src=\"img/GPU/5.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">MSI 6GB</p>",
        "54",
        "1294",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,true,5);' class=\"ui inverted violet button dr_priceButton texts\">449400</div>"],
    ["<img src=\"img/GPU/6.jpg\" class=\"dr_itemImage\">",
        "<p>GTX1060</p><p class=\"dr_align_right\">ASUS 6GB</p>",
        "55",
        "1349",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,true,6);' class=\"ui inverted violet button dr_priceButton texts\">465150</div>"],
    ["<img src=\"img/GPU/7.jpg\" class=\"dr_itemImage\">",
        "<p>RX580</p><p class=\"dr_align_right\">SAPPHIRE 8GB</p>",
        "57",
        "1432",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,true,7);' class=\"ui inverted violet button dr_priceButton texts\">487000</div>"]
];

var dbr_cpu = [
    ["<img src=\"img/CPU/0.jpg\" class=\"dr_itemImage\">",
        "<p>펜티엄 G4660</p><p class=\"dr_align_right\">인텔</p>",
        "46",
        "137",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,false,0);' id=\"\"class=\"ui inverted violet button dr_priceButton texts\">119760</div>"],
    ["<img src=\"img/CPU/1.jpg\" class=\"dr_itemImage\">",
        "<p>라이젠 3 2200G</p><p class=\"dr_align_right\">AMD</p>",
        "52",
        "184",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,false,1);' class=\"ui inverted violet button dr_priceButton texts\">168010</div>"],
    ["<img src=\"img/CPU/2.jpg\" class=\"dr_itemImage\">",
        "<p>i3 8100</p><p class=\"dr_align_right\">인텔</p>",
        "53",
        "210",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,false,2);' class=\"ui inverted violet button dr_priceButton texts\">211040</div>"],
    ["<img src=\"img/CPU/3.jpg\" class=\"dr_itemImage\">",
        "<p>라이젠 5 2400G</p><p class=\"dr_align_right\">AMD</p>",
        "54",
        "221",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,false,3);' class=\"ui inverted violet button dr_priceButton texts\">243010</div>"],
    ["<img src=\"img/CPU/4.jpg\" class=\"dr_itemImage\">",
        "<p>i5 8500</p><p class=\"dr_align_right\">인텔</p>",
        "58",
        "242",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,false,4);' class=\"ui inverted violet button dr_priceButton texts\">308560</div>"],
    ["<img src=\"img/CPU/5.jpg\" class=\"dr_itemImage\">",
        "<p>라이젠 5 2600</p><p class=\"dr_align_right\">AMD</p>",
        "55",
        "269",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,false,5);' class=\"ui inverted violet button dr_priceButton texts\">306220</div>"],
    ["<img src=\"img/CPU/6.jpg\" class=\"dr_itemImage\">",
        "<p>i5 8600</p><p class=\"dr_align_right\">인텔</p>",
        "59",
        "260",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,false,6);' class=\"ui inverted violet button dr_priceButton texts\">333930</div>"],
    ["<img src=\"img/CPU/7.jpg\" class=\"dr_itemImage\">",
        "<p>라이젠 5 2600X</p><p class=\"dr_align_right\">AMD</p>",
        "56",
        "282",
        "<div onmouseout='pricebar_hoverend();' onmouseover='GPU_hover(this,false,7);' class=\"ui inverted violet button dr_priceButton texts\">345220</div>"]
];
